name: Run Messenger Bot Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🔐 Create appstate.json from Secret
        env:
          APPSTATE_BASE64: ${{ secrets.APPSTATE_BASE64 }}
        run: |
          echo "$APPSTATE_BASE64" | base64 -d > appstate.json

      - name: 🚀 Run Bot
        run: timeout 5h node index.js
